CREATE TYPE [dbo].[TableTypePurchaseSaleBookLineItem] AS TABLE (
    [PurchaseSaleBookLineItemID]    BIGINT          NULL,
    [PurchaseSaleBookHeaderID]      BIGINT          NOT NULL,
    [FifoID]                        BIGINT          NULL,
    [PurchaseBillDate]              DATETIME        NULL,
    [PurchaseVoucherNumber]         NVARCHAR (8)    NULL,
    [PurchaseSrlNo]                 INT             NULL,
    [ItemCode]                      NVARCHAR (9)    NOT NULL,
    [ItemName]                      NVARCHAR (100)  NULL,
    [Batch]                         NVARCHAR (20)   NULL,
    [BatchNew]                      NVARCHAR (20)   NULL,
    [Quantity]                      DECIMAL (18, 2) NOT NULL,
    [FreeQuantity]                  DECIMAL (18, 2) NULL,
    [PurchaseSaleRate]              DECIMAL (18, 2) NULL,
    [EffecivePurchaseSaleRate]      DECIMAL (18, 2) NULL,
    [PurchaseSaleTypeCode]          NVARCHAR (10)   NOT NULL,
    [SurCharge]                     DECIMAL (18, 2) NULL,
    [PurchaseSaleTax]               DECIMAL (18, 2) NULL,
    [LocalCentral]                  NVARCHAR (1)    NOT NULL,
    [SGST]                          DECIMAL (18, 2) NULL,
    [IGST]                          DECIMAL (18, 2) NULL,
    [CGST]                          DECIMAL (18, 2) NULL,
    [Amount]                        DECIMAL (18, 2) NOT NULL,
    [Discount]                      DECIMAL (18, 2) NULL,
    [SpecialDiscount]               DECIMAL (18, 2) NULL,
    [DiscountQuantity]              DECIMAL (18, 2) NULL,
    [VolumeDiscount]                DECIMAL (18, 2) NULL,
    [Scheme1]                       DECIMAL (18, 2) NULL,
    [Scheme2]                       DECIMAL (18, 2) NULL,
    [IsHalfScheme]                  BIT             NOT NULL,
    [HalfSchemeRate]                DECIMAL (18, 2) NULL,
    [ConversionRate]                DECIMAL (18, 2) NULL,
    [MRP]                           DECIMAL (18, 2) NULL,
    [ExpiryDate]                    DATETIME        NULL,
    [SaleRate]                      DECIMAL (18, 2) NULL,
    [WholeSaleRate]                 DECIMAL (18, 2) NULL,
    [SpecialRate]                   DECIMAL (18, 2) NULL,
    [CostAmount]                    DECIMAL (18, 2) NULL,
    [GrossAmount]                   DECIMAL (18, 2) NULL,
    [SchemeAmount]                  DECIMAL (18, 2) NULL,
    [DiscountAmount]                DECIMAL (18, 2) NULL,
    [SurchargeAmount]               DECIMAL (18, 2) NULL,
    [TaxAmount]                     DECIMAL (18, 2) NULL,
    [SpecialDiscountAmount]         DECIMAL (18, 2) NULL,
    [VolumeDiscountAmount]          DECIMAL (18, 2) NULL,
    [TotalDiscountAmount]           DECIMAL (18, 2) NULL,
    [UsedQuantity]                  DECIMAL (18, 2) NULL,
    [BalanceQuantity]               DECIMAL (18, 2) NULL,
    [OldPurchaseSaleBookLineItemID] BIGINT          NULL,
    [CreatedBy]                     NVARCHAR (50)   NULL,
    [CreatedOn]                     DATETIME        NULL,
    [ModifiedBy]                    NVARCHAR (50)   NULL,
    [ModifiedOn]                    DATETIME        NULL);

