CREATE TABLE [dbo].[CustomerLedger] (
    [CustomerLedgerId]          INT             IDENTITY (1, 1) NOT NULL,
    [CustomerLedgerCode]        NVARCHAR (10)   NOT NULL,
    [CustomerLedgerName]        NVARCHAR (50)   NOT NULL,
    [CustomerLedgerShortName]   NVARCHAR (20)   NOT NULL,
    [Address]                   NVARCHAR (100)  NOT NULL,
    [ContactPerson]             NVARCHAR (50)   NOT NULL,
    [Mobile]                    NVARCHAR (50)   NULL,
    [OfficePhone]               NVARCHAR (50)   NULL,
    [ResidentPhone]             NVARCHAR (50)   NULL,
    [EmailAddress]              NVARCHAR (100)  NULL,
    [OpeningBal]                DECIMAL (15, 2) NULL,
    [CreditDebit]               CHAR (1)        NOT NULL,
    [TaxRetail]                 CHAR (1)        NOT NULL,
    [Status]                    BIT             NOT NULL,
    [ZSMId]                     INT             NULL,
    [ASMId]                     INT             NULL,
    [RSMId]                     INT             NULL,
    [AreaId]                    INT             NULL,
    [SalesManId]                INT             NULL,
    [RouteId]                   INT             NULL,
    [DLNo]                      NVARCHAR (20)   NOT NULL,
    [GSTNo]                     NVARCHAR (10)   NOT NULL,
    [CINNo]                     NVARCHAR (10)   NOT NULL,
    [LINNo]                     NVARCHAR (20)   NULL,
    [ServiceTaxNo]              NVARCHAR (20)   NULL,
    [PANNo]                     NVARCHAR (20)   NULL,
    [CreditLimit]               INT             NOT NULL,
    [RateTypeID]                INT             NULL,
    [IsLessExcise]              BIT             NOT NULL,
    [CustomerTypeID]            INT             NOT NULL,
    [InterestTypeID]            INT             NOT NULL,
    [MaxOSAmount]               DECIMAL (18, 2) NULL,
    [MaxNumOfOSBill]            INT             NULL,
    [MaxBillAmount]             DECIMAL (18, 2) NULL,
    [MaxGracePeriod]            INT             NULL,
    [SaleBillFormat]            NVARCHAR (10)   NULL,
    [IsFollowConditionStrictly] BIT             NOT NULL,
    [Discount]                  DECIMAL (18, 2) NULL,
    [CentralLocal]              CHAR (1)        NOT NULL,
    [CreatedBy]                 NVARCHAR (50)   NULL,
    [CreatedOn]                 DATETIME        NULL,
    [ModifiedBy]                NVARCHAR (50)   NULL,
    [ModifiedOn]                DATETIME        NULL,
    [CustomerLedgerShortDesc]   NVARCHAR (20)   NULL,
    [Telephone]                 NVARCHAR (50)   NULL,
    CONSTRAINT [PK_CustomerLedger] PRIMARY KEY CLUSTERED ([CustomerLedgerId] ASC),
    CONSTRAINT [FK_CustomerLedger_CustomerLedger] FOREIGN KEY ([ZSMId]) REFERENCES [dbo].[PersonRouteMaster] ([PersonRouteID]),
    CONSTRAINT [FK_CustomerLedger_CustomerType] FOREIGN KEY ([CustomerTypeID]) REFERENCES [dbo].[CustomerType] ([CustomerTypeId]),
    CONSTRAINT [FK_CustomerLedger_InterestType] FOREIGN KEY ([InterestTypeID]) REFERENCES [dbo].[RateType] ([RateTypeId]),
    CONSTRAINT [FK_CustomerLedger_SalesPersonMaster] FOREIGN KEY ([ASMId]) REFERENCES [dbo].[PersonRouteMaster] ([PersonRouteID]),
    CONSTRAINT [FK_CustomerLedger_SalesPersonMaster1] FOREIGN KEY ([RSMId]) REFERENCES [dbo].[PersonRouteMaster] ([PersonRouteID]),
    CONSTRAINT [FK_CustomerLedger_SalesPersonMaster2] FOREIGN KEY ([SalesManId]) REFERENCES [dbo].[PersonRouteMaster] ([PersonRouteID]),
    CONSTRAINT [FK_CustomerLedger_SalesPersonMaster3] FOREIGN KEY ([AreaId]) REFERENCES [dbo].[PersonRouteMaster] ([PersonRouteID]),
    CONSTRAINT [FK_CustomerLedger_SalesPersonMaster4] FOREIGN KEY ([RouteId]) REFERENCES [dbo].[PersonRouteMaster] ([PersonRouteID])
);

