CREATE TABLE [dbo].[FIFO] (
    [FifoID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [PurchaseSaleBookHeaderID] BIGINT          NULL,
    [VoucherNumber]            NVARCHAR (8)    NOT NULL,
    [VoucherDate]              DATETIME        NOT NULL,
    [SRLNO]                    INT             NOT NULL,
    [ItemCode]                 NVARCHAR (10)   NOT NULL,
    [PurchaseBillNo]           NVARCHAR (20)   NULL,
    [Batch]                    NVARCHAR (20)   NOT NULL,
    [ExpiryDate]               DATETIME        NULL,
    [Quantity]                 DECIMAL (18, 2) NOT NULL,
    [BalanceQuanity]           DECIMAL (18, 2) NOT NULL,
    [PurchaseTypeId]           INT             NULL,
    [PurchaseRate]             DECIMAL (18, 2) NOT NULL,
    [EffectivePurchaseRate]    DECIMAL (18, 2) NULL,
    [SaleRate]                 DECIMAL (18, 2) NOT NULL,
    [WholeSaleRate]            DECIMAL (18, 2) NULL,
    [SpecialRate]              DECIMAL (18, 2) NULL,
    [MRP]                      DECIMAL (18, 2) NOT NULL,
    [Scheme1]                  DECIMAL (18, 2) NULL,
    [Scheme2]                  DECIMAL (18, 2) NULL,
    [IsOnHold]                 BIT             NULL,
    [OnHoldRemarks]            NVARCHAR (200)  NULL,
    [MfgDate]                  DATETIME        NULL,
    [UPC]                      NVARCHAR (12)   NULL,
    CONSTRAINT [PK_FIFO] PRIMARY KEY CLUSTERED ([FifoID] ASC),
    CONSTRAINT [FK_FIFO_PurchaseSaleBookHeader] FOREIGN KEY ([PurchaseSaleBookHeaderID]) REFERENCES [dbo].[PurchaseSaleBookHeader] ([PurchaseSaleBookHeaderID])
);

