CREATE TABLE [dbo].[ItemMaster] (
    [ItemID]                  INT             IDENTITY (1, 1) NOT NULL,
    [ItemCode]                NVARCHAR (9)    NOT NULL,
    [ItemName]                NVARCHAR (30)   NULL,
    [CompanyID]               INT             NOT NULL,
    [ConversionRate]          DECIMAL (18, 2) NULL,
    [ShortName]               NVARCHAR (10)   NULL,
    [Packing]                 NVARCHAR (10)   NULL,
    [PurchaseRate]            DECIMAL (18, 2) NULL,
    [MRP]                     DECIMAL (18, 2) NOT NULL,
    [SaleRate]                DECIMAL (18, 2) NULL,
    [SpecialRate]             DECIMAL (18, 2) NULL,
    [WholeSaleRate]           DECIMAL (18, 2) NULL,
    [SaleExcise]              DECIMAL (18, 2) NULL,
    [SurchargeOnSale]         DECIMAL (18, 2) NULL,
    [TaxOnSale]               DECIMAL (18, 2) NULL,
    [Scheme1]                 DECIMAL (18, 2) NULL,
    [Scheme2]                 DECIMAL (18, 2) NULL,
    [PurchaseExcise]          DECIMAL (18, 2) NULL,
    [UPC]                     NVARCHAR (16)   NULL,
    [IsHalfScheme]            BIT             NOT NULL,
    [IsQTRScheme]             BIT             NOT NULL,
    [SpecialDiscount]         DECIMAL (18, 2) NULL,
    [SpecialDiscountOnQty]    DECIMAL (18, 2) NULL,
    [IsFixedDiscount]         BIT             NOT NULL,
    [FixedDiscountRate]       DECIMAL (18, 2) NULL,
    [MaximumQty]              DECIMAL (18, 2) NULL,
    [MaximumDiscount]         DECIMAL (18, 2) NULL,
    [SurchargeOnPurchase]     DECIMAL (18, 2) NULL,
    [TaxOnPurchase]           DECIMAL (18, 2) NULL,
    [DiscountRecieved]        DECIMAL (18, 2) NULL,
    [SpecialDiscountRecieved] DECIMAL (18, 2) NULL,
    [QtyPerCase]              DECIMAL (18, 2) NULL,
    [Location]                NVARCHAR (5)    NULL,
    [MinimumStock]            INT             NULL,
    [MaximumStock]            INT             NULL,
    [SaleTypeId]              INT             NOT NULL,
    [PurchaseTypeId]          INT             NOT NULL,
    [Status]                  BIT             NOT NULL,
    [CreatedBy]               NVARCHAR (50)   NULL,
    [CreatedOn]               DATETIME        NULL,
    [ModifiedBy]              NVARCHAR (50)   NULL,
    [ModifiedOn]              DATETIME        NULL,
    [BATCH]                   NVARCHAR (20)   NULL,
    [ExpiryDate]              DATETIME        NULL,
    [OpeningQty]              DECIMAL (18, 2) NULL,
    [ClosingQty]              DECIMAL (18, 2) NULL,
    [SaltCode]                NVARCHAR (50)   NULL,
    [SaltName]                NVARCHAR (100)  NULL,
    [HSNCode]                 NVARCHAR (18)   NOT NULL,
    CONSTRAINT [PK_ItemMaster_1] PRIMARY KEY CLUSTERED ([ItemID] ASC),
    CONSTRAINT [FK_ItemMaster_AccountLedgerMaster] FOREIGN KEY ([SaleTypeId]) REFERENCES [dbo].[AccountLedgerMaster] ([AccountLedgerID]),
    CONSTRAINT [FK_ItemMaster_AccountLedgerMasterPurchase] FOREIGN KEY ([PurchaseTypeId]) REFERENCES [dbo].[AccountLedgerMaster] ([AccountLedgerID]),
    CONSTRAINT [FK_ItemMaster_CompanyMaster] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[CompanyMaster] ([CompanyId]),
    CONSTRAINT [FK_ItemMaster_HSNCode] FOREIGN KEY ([HSNCode]) REFERENCES [dbo].[HSNCode] ([HSNCode])
);

