CREATE TABLE [dbo].[SupplierLedger] (
    [SupplierLedgerId]        INT             IDENTITY (1, 1) NOT NULL,
    [SupplierLedgerCode]      NVARCHAR (10)   NOT NULL,
    [SupplierLedgerName]      NVARCHAR (50)   NOT NULL,
    [SupplierLedgerShortName] NVARCHAR (20)   NOT NULL,
    [Address]                 NVARCHAR (100)  NOT NULL,
    [ContactPerson]           NVARCHAR (50)   NOT NULL,
    [Mobile]                  NVARCHAR (50)   NULL,
    [Pager]                   NVARCHAR (50)   NULL,
    [Fax]                     NVARCHAR (50)   NULL,
    [OfficePhone]             NVARCHAR (50)   NULL,
    [ResidentPhone]           NVARCHAR (50)   NULL,
    [EmailAddress]            NVARCHAR (100)  NULL,
    [OpeningBal]              DECIMAL (15, 2) NULL,
    [CreditDebit]             CHAR (1)        NOT NULL,
    [TaxRetail]               CHAR (1)        NOT NULL,
    [Status]                  BIT             NOT NULL,
    [AreaId]                  INT             NOT NULL,
    [CreatedBy]               NVARCHAR (50)   NULL,
    [CreatedOn]               DATETIME        NULL,
    [ModifiedBy]              NVARCHAR (50)   NULL,
    [ModifiedOn]              DATETIME        NULL,
    [SupplierLedgerShortDesc] NVARCHAR (20)   NULL,
    [PurchaseTypeID]          INT             NOT NULL,
    [DLNo]                    NVARCHAR (20)   NULL,
    [GSTNo]                   NVARCHAR (10)   NULL,
    [CINNo]                   NVARCHAR (10)   NULL,
    [LINNo]                   NVARCHAR (20)   NULL,
    [ServiceTaxNo]            NVARCHAR (20)   NULL,
    [PANNo]                   NVARCHAR (20)   NULL,
    CONSTRAINT [PK_SupplierLedger] PRIMARY KEY CLUSTERED ([SupplierLedgerId] ASC),
    CONSTRAINT [FK_SupplierLedger_PurchaseLedger] FOREIGN KEY ([PurchaseTypeID]) REFERENCES [dbo].[AccountLedgerMaster] ([AccountLedgerID]),
    CONSTRAINT [FK_SupplierLedger_SalesPersonMaster] FOREIGN KEY ([AreaId]) REFERENCES [dbo].[PersonRouteMaster] ([PersonRouteID])
);

