//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLedgerType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountLedgerType()
        {
            this.AccountLedgerMaster = new HashSet<AccountLedgerMaster>();
        }
    
        public int AccountLedgerTypeID { get; set; }
        public string AccountLedgerTypeName { get; set; }
        public string SystemName { get; set; }
        public bool Status { get; set; }
        public string CodeStartWith { get; set; }
        public bool IsUsedInAccountLedgerMasterForm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountLedgerMaster> AccountLedgerMaster { get; set; }
    }
}
