//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLedgerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountLedgerMaster()
        {
            this.AccountLedgerMaster1 = new HashSet<AccountLedgerMaster>();
            this.AccountLedgerMaster11 = new HashSet<AccountLedgerMaster>();
            this.ItemMaster = new HashSet<ItemMaster>();
            this.ItemMaster1 = new HashSet<ItemMaster>();
            this.SupplierLedger = new HashSet<SupplierLedger>();
        }
    
        public int AccountLedgerID { get; set; }
        public string AccountLedgerCode { get; set; }
        public string AccountLedgerName { get; set; }
        public int AccountLedgerTypeId { get; set; }
        public decimal OpeningBalance { get; set; }
        public string CreditDebit { get; set; }
        public int AccountTypeId { get; set; }
        public Nullable<int> DebitControlCodeID { get; set; }
        public Nullable<int> CreditControlCodeID { get; set; }
        public bool Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> SalePurchaseTaxType { get; set; }
    
        public virtual AccountLedgerType AccountLedgerType { get; set; }
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountLedgerMaster> AccountLedgerMaster1 { get; set; }
        public virtual AccountLedgerMaster AccountLedgerMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountLedgerMaster> AccountLedgerMaster11 { get; set; }
        public virtual AccountLedgerMaster AccountLedgerMaster3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMaster> ItemMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMaster> ItemMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierLedger> SupplierLedger { get; set; }
    }
}
