//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerLedger()
        {
            this.CustomerCompanyDiscountRef = new HashSet<CustomerCompanyDiscountRef>();
        }
    
        public int CustomerLedgerId { get; set; }
        public string CustomerLedgerCode { get; set; }
        public string CustomerLedgerName { get; set; }
        public string CustomerLedgerShortName { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string Mobile { get; set; }
        public string OfficePhone { get; set; }
        public string ResidentPhone { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public string CreditDebit { get; set; }
        public string TaxRetail { get; set; }
        public bool Status { get; set; }
        public Nullable<int> ZSMId { get; set; }
        public Nullable<int> ASMId { get; set; }
        public Nullable<int> RSMId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> SalesManId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public string DLNo { get; set; }
        public string GSTNo { get; set; }
        public string CINNo { get; set; }
        public string LINNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public string PANNo { get; set; }
        public int CreditLimit { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public bool IsLessExcise { get; set; }
        public int CustomerTypeID { get; set; }
        public int InterestTypeID { get; set; }
        public Nullable<decimal> MaxOSAmount { get; set; }
        public Nullable<int> MaxNumOfOSBill { get; set; }
        public Nullable<decimal> MaxBillAmount { get; set; }
        public Nullable<int> MaxGracePeriod { get; set; }
        public string SaleBillFormat { get; set; }
        public bool IsFollowConditionStrictly { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string CentralLocal { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CustomerLedgerShortDesc { get; set; }
        public string Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCompanyDiscountRef> CustomerCompanyDiscountRef { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual RateType RateType { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster1 { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster2 { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster3 { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster4 { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster5 { get; set; }
    }
}
