//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIFO()
        {
            this.PurchaseSaleBookLineItem = new HashSet<PurchaseSaleBookLineItem>();
            this.TempPurchaseSaleBookLineItem = new HashSet<TempPurchaseSaleBookLineItem>();
        }
    
        public long FifoID { get; set; }
        public Nullable<long> PurchaseSaleBookHeaderID { get; set; }
        public string VoucherNumber { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public int SRLNO { get; set; }
        public string ItemCode { get; set; }
        public string PurchaseBillNo { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal BalanceQuanity { get; set; }
        public Nullable<int> PurchaseTypeId { get; set; }
        public decimal PurchaseRate { get; set; }
        public Nullable<decimal> EffectivePurchaseRate { get; set; }
        public decimal SaleRate { get; set; }
        public Nullable<decimal> WholeSaleRate { get; set; }
        public Nullable<decimal> SpecialRate { get; set; }
        public decimal MRP { get; set; }
        public Nullable<decimal> Scheme1 { get; set; }
        public Nullable<decimal> Scheme2 { get; set; }
        public Nullable<bool> IsOnHold { get; set; }
        public string OnHoldRemarks { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public string UPC { get; set; }
    
        public virtual PurchaseSaleBookHeader PurchaseSaleBookHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSaleBookLineItem> PurchaseSaleBookLineItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempPurchaseSaleBookLineItem> TempPurchaseSaleBookLineItem { get; set; }
    }
}
