//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MenuID { get; set; }
        public string MenuKey { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> PrivledgeId { get; set; }
        public bool Status { get; set; }
    
        public virtual Privledges Privledges { get; set; }
    }
}
