//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseSaleEntryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseSaleEntryType()
        {
            this.PurchaseSaleEntryForm = new HashSet<PurchaseSaleEntryForm>();
        }
    
        public int PurchaseSaleEntryTypeID { get; set; }
        public string PurchaseSaleTypeCode { get; set; }
        public string PurchaseSaleTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSaleEntryForm> PurchaseSaleEntryForm { get; set; }
    }
}
