//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePrivledges
    {
        public int RolePrivledgeID { get; set; }
        public int RoleId { get; set; }
        public int PrivledgeId { get; set; }
    
        public virtual Privledges Privledges { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
