//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN
    {
        public long TrnID { get; set; }
        public long PurchaseSaleBookHeaderID { get; set; }
        public string VoucherNumber { get; set; }
        public string VoucherTypeCode { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string LedgerType { get; set; }
        public string LedgerTypeCode { get; set; }
        public string NARRATION { get; set; }
        public decimal Amount { get; set; }
        public string DebitCredit { get; set; }
        public string Status { get; set; }
        public bool IsChequeClear { get; set; }
        public Nullable<System.DateTime> ChequeClearedDate { get; set; }
        public string ChequeNumber { get; set; }
    
        public virtual PurchaseSaleBookHeader PurchaseSaleBookHeader { get; set; }
    }
}
